apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{PROJECT_FILE_NAME}}
spec:
  parentRefs:
    - name: backend-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/{{PROJECT_FILE_NAME}}
      backendRefs:
        - name: {{PROJECT_FILE_NAME}}
          port: 8080
