apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml
  - ./resources/db-migration-job.yaml

namespace: user
commonLabels:
  app: {{PROJECT_FILE_NAME}}

configMapGenerator:
  - name: {{PROJECT_FILE_NAME}}-config
    envs:
      - ./files/.env
