#!/usr/bin/env bash

supervisor-config

if [ ! -z "$SCHEDULE" ]; then
* * * * * cd  /var/app && php artisan schedule:run >> /dev/null 2>&1
fi;

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
