#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Drmovi\MonorepoGenerator\Commands\MonorepoInitCommand());
$application->add(new \Drmovi\MonorepoGenerator\Commands\MonorepoPackageCreateCommand());
$application->add(new \Drmovi\MonorepoGenerator\Commands\MonorepoPackageDeleteCommand());
$application->run();
