apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/route.yaml
  - resources/service-account.yaml
#  - resources/db-migration-job.yaml
namespace: backend
commonLabels:
  app: {{PROJECT_FILE_NAME}}
configMapGenerator:
  - name: {{PROJECT_FILE_NAME}}-config
    envs:
      - ./files/.env
