apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: {{PROJECT_FILE_NAME}}
      context: ../../../
      docker:
        dockerfile: ./Dockerfile
        buildArgs:
          MICROSERVICE: {{PROJECT_FILE_NAME}}
      sync:
        manual:

deploy:
  kubectl: {}

profiles:
  - name: local
    patches:
      - op: add
        path: /build/artifacts/0/docker/buildArgs/APP_ENV
        value: local
      - op: add
        path: /build/artifacts/0/sync/manual
        value:
          - src: ./{{PACKAGES_PATH}}/{{PROJECT_FILE_NAME}}/**
            dest: /var/app/{{PACKAGES_PATH}}/{{PROJECT_FILE_NAME}}/
          - src: ./{{SHARED_PACKAGES_PATH}}/
            dest: /var/app/{{SHARED_PACKAGES_PATH}}/
          - src: ./vendor/**
            dest: /var/app/vendor/

    manifests:
      kustomize:
        paths:
          - ./overlay/local
    deploy:
      kubectl: {}


  - name: prod
    manifests:
      kustomize:
        paths:
          - ./overlay/prod

