<?php

namespace Drmovi\MonorepoGenerator\Traits;

use Drmovi\MonorepoGenerator\Utils\FileUtil;

trait CopyStubFiles
{

    private function copyStubFiles(
        string $source,
        string $destination,
        string $composerName,
        string $packageNamespace,
        string $packageName,
        string $appPath,
        string $packagePath
    ): void
    {
        FileUtil::copyDirectory(
            source: __DIR__ . '/../../stubs/' . $source,
            destination: $destination,
            replacements: [
                '{{APP_PATH}}' => $appPath,
                '{{PACKAGES_PATH}}' => $packagePath,
                '{{PROJECT_COMPOSER_NAME}}' => $composerName,
                '{{PROJECT_VERSION}}' => '1.0.0',
                '{{PROJECT_DESCRIPTION}}' => 'This is a package generated by drmovi PHP Package Generator',
                '{{PROJECT_COMPOSER_NAMESPACE}}' => str_replace('\\', '\\\\', $packageNamespace),
                '{{PROJECT_NAMESPACE}}' => $packageNamespace,
                '{{PROJECT_CLASS_NAME}}' => ucwords($packageName),
                '{{PROJECT_FILE_NAME}}' => strtolower($packageName),
            ]);
    }
}
