apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{PROJECT_FILE_NAME}}
  labels:
    app: {{PROJECT_FILE_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      name: {{PROJECT_FILE_NAME}}
      labels:
        app: {{PROJECT_FILE_NAME}}
    spec:
      containers:
        - name: {{PROJECT_FILE_NAME}}
          image: {{PROJECT_FILE_NAME}}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{PROJECT_FILE_NAME}}-config
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 750Mi
          livenessProbe:
            httpGet:
              path: /service-health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /service-health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{PROJECT_FILE_NAME}}
